apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://github.com/gnomesoftuk/gitops-argocd-apps.git
      targetRevision: HEAD
      path: ./argo/namespaces
    - repoURL: https://github.com/gnomesoftuk/gitops-argocd-apps.git
      targetRevision: HEAD
      path: ./argo/apps

