apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/gnomesoftuk/gitops-argocd-demoapp.git
    targetRevision: HEAD
    path: ./infra/k8s/
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-frontend
  syncPolicy:
    syncOptions:
    automated:
      prune: true
      selfHeal: true