apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/gnomesoftuk/nginx-demo.git
    targetRevision: HEAD
    path: ./infra/kustomize/overlays/default
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    syncOptions:
    automated:
      prune: true
      selfHeal: true